abstract class UI {
  static const String findUp = 'find_up',
      add = 'add',
      edit = 'edit',
      layout = 'layout',
      about = 'about',
      cancel = 'cancel',
      confirm = 'confirm',
      folders = 'folders',
      addFolder = 'add_folder',
      folderNotExists = 'folder_not_exists',
      loading = 'loading',
      ok = 'ok',
      modify = 'modify',
      continue_ = 'continue',
      next = 'next',
      accept = 'accept',
      back = 'back',
      startGame = 'start_game',
      settings = 'settings',
      removeCache = 'remove_cache',
      removeData = 'removeData',
      exit = 'exit',
      alertRemoveCacheTitle = 'alert_remove_cache_title',
      alertRemoveCacheContent = 'alert_remove_cache_content',
      alertRemoveDataTitle = 'alert_remove_data_title',
      alertRemoveDataContent = 'alert_remove_data_content',
      open = 'open',
      remove = 'remove',
      removed = 'removed',
      saveImage = 'save_image',
      save = 'save',
      play = 'play',
      playAgain = 'play_again',
      playNext = 'play_next',
      file = 'file',
      wait = 'wait',
      fileList = 'file_list',
      fileInfo = 'file_info',
      dontShowAgain = 'dont_show_again',
      unlock = 'unlock',
      reload = 'reload',
      name = 'name',
      path = 'path',
      ilpAuthor = 'ilp_author',
      ilpVersion = 'ilp_version',
      ilpName = 'ilp_name',
      ilpDesc = 'ilp_desc',
      link = 'ilp_link',
      cover = 'cover',
      ilpCover = 'ilp_cover',
      ilpChangeCover = 'ilp_change_cover',
      imageLength = 'image_length',
      imageLengthStr = 'image_length_str',
      empty = 'empty',
      image = 'image',
      inGame = 'in_game',
      builtIn = 'built_in',
      seed = 'seed',
      clicks = 'clicks',
      usedTime = 'used_time',
      timeLeft = 'time_left',
      finish = 'finish',
      help = 'help',
      contactDeveloper = 'contact_developer',
      saved = 'saved',
      saving = 'saving',
      contentCannotEmpty = 'contentCannotEmpty',
      resolution = 'resolution',
      layerCount = 'layerCount',
      url = 'url',
      error = 'error',
      search = 'search',
      sort = 'sort',
      updateTime = 'update_time',
      vote = 'vote',
      downloading = 'downloading',
      fileSize = 'file_size',
      unfound = 'unfound';

  static Map<String, Map<String, String>> get keys {
    return {
      'en_US': {
        findUp: 'Find Up!',
        edit: 'Edit',
        wait: 'Please wait',
        layout: 'Layout(grid or list)',
        about: 'About',
        loading: 'Loading',
        cancel: 'Cancel',
        confirm: 'Confirm',
        folders: 'Folders',
        add: 'Add',
        addFolder: 'Add folder',
        name: 'Name',
        path: 'Path',
        folderNotExists: '%s not exists',
        fileList: 'Files',
        ok: 'OK',
        continue_: 'Continue',
        next: 'Next',
        accept: 'Accept',
        back: 'Back',
        startGame: 'Start Game',
        settings: 'Settings / 设置',
        removeCache: 'Clear Cache',
        removeData: 'Clear Data',
        exit: 'Exit',
        layerCount: 'Layer count',
        alertRemoveCacheTitle: 'Are you sure to remove the caches?',
        alertRemoveCacheContent: [
          'Include:',
          'Network caches',
        ].join('\n'),
        alertRemoveDataTitle: 'Are you sure to removed all data?',
        alertRemoveDataContent: [
          'Include:',
          'Network caches',
          'Unlocked layers data',
        ].join('\n'),
        open: 'Open',
        remove: 'Remove',
        removed: 'Removed',
        saveImage: 'Save image',
        play: 'Play',
        playAgain: 'Play again',
        playNext: 'Next',
        save: 'Save',
        dontShowAgain: 'Dont\'t show again',
        unlock: 'Unlocked',
        reload: 'Reload',
        ilpAuthor: 'Author',
        ilpVersion: 'Version',
        ilpName: 'File name',
        ilpDesc: 'File description',
        link: 'Link',
        cover: 'Cover',
        modify: 'Modify',
        ilpCover: 'Cover',
        ilpChangeCover: 'Select',
        fileInfo: 'File information',
        file: 'File',
        imageLength: 'Number of pictures',
        imageLengthStr: '%s pictures',
        empty: 'Empty',
        resolution: 'Image resolution',
        image: 'Image',
        inGame: 'In-game',
        seed: 'Seed',
        clicks: 'Click Times',
        usedTime: 'Used time',
        timeLeft: 'Time left',
        finish: 'Finish',
        help: 'Help',
        builtIn: 'Built-in',
        contactDeveloper: 'Contact the developer',
        saved: 'Saved to',
        saving: 'Saving to file',
        contentCannotEmpty: 'Content cannot be empty',
        url: 'Url',
        error: 'Error',
        search: 'Search',
        sort: 'Sort',
        updateTime: 'Last update time',
        vote: 'Vote up',
        downloading: 'Downloading',
        fileSize: 'File size',
        unfound: 'Unfound',
      },
      'zh_CN': {
        findUp: '找起来！',
        add: '添加',
        modify: '修改',
        edit: '编辑',
        wait: '请稍候',
        path: '路径',
        layout: '布局(图标或列表)',
        about: '关于',
        loading: '读取中',
        cancel: '取消',
        confirm: '确认',
        folders: '文件夹',
        addFolder: '添加文件夹',
        name: '名称',
        folderNotExists: '%s 文件夹不存在',
        fileList: '文件列表',
        ok: 'OK',
        continue_: '继续',
        next: '下一步',
        layerCount: '图层数量',
        error: '错误',
        accept: '接受',
        back: '返回',
        startGame: '开始游戏',
        settings: '设置 / Settings',
        removeCache: '清空缓存',
        removeData: '清空所有数据',
        exit: '退出',
        alertRemoveCacheTitle: '确认清空缓存？',
        alertRemoveCacheContent: [
          '包括：',
          '网络图片缓存',
        ].join('\n'),
        alertRemoveDataTitle: '确认清空所有数据？',
        alertRemoveDataContent: [
          '包括：',
          '网络图片缓存',
          '已解锁的图层记录',
        ].join('\n'),
        open: '打开',
        remove: '移除',
        removed: '已移除',
        saveImage: '保存图片',
        play: '打开',
        playAgain: '再玩一次',
        playNext: '下一关',
        save: '保存',
        dontShowAgain: '不再显示',
        unlock: '已解锁',
        reload: '刷新',
        ilpAuthor: '作者名称',
        ilpVersion: '版本',
        ilpName: '文件主题',
        ilpDesc: '描述',
        link: '链接',
        cover: '封面',
        ilpCover: '文件封面(默认使用第一张图片的封面)',
        ilpChangeCover: '更换',
        fileInfo: '文件信息',
        file: '文件',
        imageLength: '图片数量',
        imageLengthStr: '%s 张图片',
        empty: '内容为空',
        resolution: '图片分辨率',
        image: '图片',
        inGame: '附带的游戏',
        seed: '种子',
        clicks: '点击次数',
        usedTime: '已使用时间',
        timeLeft: '所剩时间',
        finish: '已完成',
        help: '帮助',
        builtIn: '内置',
        contactDeveloper: '开发者的联系信息',
        saved: '已保存到',
        saving: '正在保存',
        contentCannotEmpty: '内容不能为空',
        url: '网址',
        search: '搜索',
        sort: '排序',
        updateTime: '最后更新时间',
        vote: '点赞量',
        downloading: '正在下载',
        fileSize: '文件大小',
        unfound: '未找到的',
      }
    };
  }
}
