import 'package:game/ui.dart';
import 'package:get/get.dart';

class WindowsUI implements Translations {
  static const ilpEditor = 'game_editor',
      releaseMouseToOpenFile = 'drop_open_file',
      ilpEditorHelpTitle = 'ilp_editor_help_title',
      ilpEditorStep1Title = 'ilp_editor_step_1',
      ilpEditorStep1Content = 'ilp_editor_step_1_c',
      ilpEditorStep2TitleUse = 'ilp_editor_step_2',
      ilpEditorStep2TitleBtn = 'ilp_editor_step_2_btn',
      ilpEditorStep2TitleExport = 'ilp_editor_step_2_export',
      ilpEditorStep2Content = 'ilp_editor_step_2_c',
      ilpEditorStep3Title = 'ilp_editor_step_3',
      ilpEditorStep3Content = 'ilp_editor_step_3_c',
      ilpEditorStep4Title = 'ilp_editor_step_4',
      ilpEditorStep4Content = 'ilp_editor_step_4_c',
      dragToSort = 'drag_to_sort',
      clickToModify = 'click_to_modify',
      ilpEditorConfigFileEmpty = 'ilp_editor_no_file',
      ilpEditorConfigFileList = 'ilp_editor_config_file_list',
      ilpEditorEmptyTip1Title = 'ilp_editor_empty_tip_1_title',
      ilpEditorEmptyTip1Btn = 'ilp_editor_empty_tip_1_btn',
      ilpEditorEmptyTip2Title = 'ilp_editor_empty_tip_2_title',
      ilpEditorEmptyTip2Content = 'ilp_editor_empty_tip_2_content',
      ilpEditorEmptyTip2Btn = 'ilp_editor_empty_tip_2_btn',
      ilpEditorValidatingFile = 'ilp_editor_validating_file',
      ilpEditorValidating = 'ilp_editor_validating',
      ilpEditorConsistent = 'ilp_editor_consistent',
      ilpEditorInconsistent = 'ilp_editor_inconsistent',
      ilpEditorFileLength = 'ilpEditorFileLength',
      ilpEditorNameInconsistent = 'ilpEditorNameInconsistent',
      ilpEditorAuthorInconsistent = 'ilpEditorAuthorInconsistent',
      ilpEditorDescInconsistent = 'ilpEditorDescInconsistent',
      ilpEditorLinksInconsistent = 'ilpEditorLinksInconsistent',
      ilpEditorImagesInconsistent = 'ilpEditorImagesInconsistent',
      ilpEditorVersionInconsistent = 'ilpEditorVersionInconsistent',
      ilpEditorModifyImageName = 'ilpEditorModifyImageName',
      ilpEditorImageName = 'ilpEditorImageName',
      ilpEditorInputImageName = 'ilpEditorInputImageName',
      ilpEditorRemoveLink = 'ilpEditorRemoveLink',
      ilpEditorFileExisted = 'ilpEditorFileExisted',
      ilpEditorFilesNotExist = 'ilpEditorFilesNotExist',
      playtest = 'playtest',
      openFolder = 'open_folder',
      ilpEditorLinkProtocolLimit = 'ilpEditorLinkProtocolLimit',
      ilpEditorFilePath = 'ilpEditorFilePath',
      ilpEditorVersionLimit = 'ilpEditorVersionLimit',
      ilpVersionTip = 'ilpVersionTip',
      steamWorkshop = 'steamWorkShop',
      steamAuthorInfo = 'steamAuthorInfo',
      steamOpenAuthorInfoPage = 'steamOpenAuthorInfoPage',
      steamAuthorOtherFiles = 'steamAuthorOtherFiles',
      steamSubscribeAndDownload = 'steamSubscribeAndDownload',
      steamSubscribed = 'steamSubscribed',
      steamUnSubscribe = 'steamUnSubscribe',
      steamUploading = 'steamUploading',
      steamUploadSuccess = 'steamUploadSuccess',
      shareToSteam = 'shareToSteam',
      viewFileInSteam = 'viewFileInSteam',
      saveToILPFile = 'save_to_ilp_file',
      uploadAgreement = 'upload_agreement',
      agreementName = 'agreement_name',
      selectSteamFileToUpdate = 'selectSteamFileToUpdate',
      steamMyFiles = 'steamMyFiles',
      or = 'or',
      dragToMove = 'dragToMove',
      clickToFind = 'clickToFind',
      doubleClickToReset = 'doubleClickToReset',
      scrollToScale = 'scrollToScale',
      style = 'style',
      styleAnime = 'Anime',
      styleRealistic = 'Realistic',
      stylePixel = 'Pixel',
      styleOther = 'Other',
      styleAncientChinese = 'Ancient Chinese',
      shape = 'Shape',
      landscape = 'Landscape',
      portrait = 'Portrait',
      square = 'Square',
      ageRating = 'AgeRating',
      ageEveryone = 'Everyone',
      ageQuestionable = 'Questionable',
      ageMature = 'Mature',
      customTags = 'customTags',
      tags = 'tags',
      openInSteam = 'openInSteam',
      fileSize = 'file_ize',
      exportLogoExamplePSD = 'exportLogoExamplePSD',
      openInBrowser = 'openInBrowser';

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          ...UI.keys['en_US']!,
          ilpEditor: 'Game Editor',
          releaseMouseToOpenFile: 'Open file',
          ilpEditorHelpTitle: 'How to use Photoshop export .ilp config file?',
          ilpEditorStep1Title:
              'Use Photoshop to draw a picture and some layers',
          ilpEditorStep1Content:
              'Each layer group can contain multiple layers with different content in the same position (recommended)\n'
                  'The game mechanism will randomly draw one layer or two layers within the same group to be placed on the left or right.\n'
                  'Layers without groups will be displayed randomly on the left or right',
          ilpEditorStep2TitleUse: 'Use',
          ilpEditorStep2TitleBtn: 'the PhotoShop plugin',
          ilpEditorStep2TitleExport: 'to export files',
          ilpEditorStep2Content:
              'It will export one .json file and many .png files',
          ilpEditorStep3Title: 'Click the [+] button to add some json files',
          ilpEditorStep3Content:
              'An ilp file containing multiple images can tell a complete story',
          ilpEditorStep4Title:
              'Fill in the information on the left side, save it as game file',
          ilpEditorStep4Content: '',
          dragToSort: 'Drag to sort',
          clickToModify: 'click to modify',
          ilpEditorConfigFileEmpty: 'No config file',
          ilpEditorConfigFileList: 'Config file list',
          ilpEditorEmptyTip1Title: 'How to make the ilp config file',
          ilpEditorEmptyTip1Btn: 'View Help',
          ilpEditorEmptyTip2Title: 'How to add the ilp config files?',
          ilpEditorEmptyTip2Content:
              'Drag some ilp config files to this area, or\n',
          ilpEditorEmptyTip2Btn: 'Select files',
          ilpEditorValidatingFile: 'Validating file',
          ilpEditorValidating: 'Validating',
          ilpEditorConsistent: 'Consistent',
          ilpEditorInconsistent: 'Inconsistent',
          ilpEditorNameInconsistent: 'Inconsistent file name',
          ilpEditorAuthorInconsistent: 'Inconsistent author name',
          ilpEditorDescInconsistent: 'Inconsistent description',
          ilpEditorLinksInconsistent: 'Inconsistent links',
          ilpEditorImagesInconsistent: 'Inconsistent images',
          ilpEditorVersionInconsistent: 'Inconsistent version',
          ilpEditorFileLength: 'File length',
          ilpEditorModifyImageName: 'Modify image name',
          ilpEditorImageName: 'Image name',
          ilpEditorInputImageName: 'Image name cannot be empty',
          ilpEditorRemoveLink: 'Remove link',
          ilpEditorFileExisted: 'File existed',
          ilpEditorFilesNotExist: 'Some files not exist',
          openFolder: 'Open folder',
          playtest: 'Playtest',
          ilpEditorLinkProtocolLimit: 'Only https link protocol is supported',
          ilpEditorFilePath: 'File path',
          ilpEditorVersionLimit:
              'The version number needs to be greater than 0',
          ilpVersionTip: 'Start from 1 and keep +1 for update this file',
          steamWorkshop: 'Steam Workshop',
          steamAuthorInfo: 'Author Info',
          steamOpenAuthorInfoPage: 'Click to open steam user page',
          steamAuthorOtherFiles: 'Other Files by the Author',
          steamSubscribeAndDownload: 'Subscribe And Download',
          steamSubscribed: 'Subscribed',
          steamUnSubscribe: 'UnSubscribe',
          steamUploading: 'Uploading To Steam',
          shareToSteam: 'Share To Steam Workshop',
          steamUploadSuccess: 'Upload success',
          viewFileInSteam: 'View file in Steam',
          saveToILPFile: 'Save to ilp file',
          uploadAgreement: 'By uploading file, you agree to ',
          agreementName: 'the workshop terms of service',
          selectSteamFileToUpdate: 'Select steam file to update',
          steamMyFiles: 'My steam files',
          or: 'Or',
          dragToMove: 'Press and hold to move the image',
          clickToFind: 'Click to find out the difference',
          doubleClickToReset: 'Double click to reset',
          scrollToScale: 'Scroll wheel to scale the image',
          style: 'Style',
          styleAnime: 'Anime Style',
          styleRealistic: 'Realistic Style',
          stylePixel: 'Pixel Style',
          styleAncientChinese: 'Ancient Chinese',
          styleOther: 'Other',
          shape: 'Shape',
          landscape: 'Landscape',
          portrait: 'Portrait',
          square: 'Square',
          ageRating: 'Age rating',
          ageEveryone: 'Everyone',
          ageQuestionable: 'Questionable',
          ageMature: 'Mature',
          customTags: 'Custom tag',
          tags: 'Tags',
          openInSteam: 'Open in steam',
          fileSize: 'File size',
          exportLogoExamplePSD: 'Export the example .psd file',
          openInBrowser: 'Open in browser',
        },
        'zh_CN': {
          ...UI.keys['zh_CN']!,
          ilpEditor: '游戏编辑器',
          releaseMouseToOpenFile: '松开鼠标打开文件',
          ilpEditorHelpTitle: '怎么使用Photoshop制作ILP配置文件？',
          ilpEditorStep1Title: '使用Photoshop绘制图片和一些图层',
          ilpEditorStep1Content: '每个图层组都可以包含多个相同位置（建议）不同内容的图层\n'
              '游戏机制会随机抽出同一组内一个图层或两个图层摆放在左右两边。\n'
              '没有组的图层会随机显示(或不显示)在左右两边',
          ilpEditorStep2TitleUse: '使用',
          ilpEditorStep2TitleBtn: 'PhotoShop插件',
          ilpEditorStep2TitleExport: '按指导导出所需文件',
          ilpEditorStep2Content: '它会导出一个.json文件和一些图片文件',
          ilpEditorStep3Title: '点击编辑器的【+】按钮添加json文件',
          ilpEditorStep3Content: '一个包含多个图像的 ilp 文件可以讲述一个完整的故事',
          ilpEditorStep4Title: '填好左侧的信息就可以保存为ilp文件（即游戏文件）',
          ilpEditorStep4Content: '',
          dragToSort: '拖动排序',
          clickToModify: '点击修改',
          ilpEditorConfigFileEmpty: '请添加ILP配置文件',
          ilpEditorConfigFileList: 'ILP配置文件列表',
          ilpEditorEmptyTip1Title: '如何制作ILP配置文件',
          ilpEditorEmptyTip1Btn: '查看帮助',
          ilpEditorEmptyTip2Title: '如何添加ILP配置文件',
          ilpEditorEmptyTip2Content: '可以 拖动一个或多个ILP配置文件到此区域 或 \n',
          ilpEditorEmptyTip2Btn: '添加一个或多个ILP配置文件',
          ilpEditorValidatingFile: '正在验证ilp文件的完整性',
          ilpEditorValidating: '检查中',
          ilpEditorConsistent: '一致',
          ilpEditorInconsistent: '不一致',
          ilpEditorNameInconsistent: '文件主题不一致',
          ilpEditorAuthorInconsistent: '作者名称不一致',
          ilpEditorDescInconsistent: '描述不一致',
          ilpEditorLinksInconsistent: '链接不一致',
          ilpEditorImagesInconsistent: '图片内容不一致',
          ilpEditorVersionInconsistent: '版本不一致',
          ilpEditorFileLength: '文件长度',
          ilpEditorModifyImageName: '修改图片名称',
          ilpEditorImageName: '图片名称',
          ilpEditorInputImageName: '图片名称不能为空',
          ilpEditorRemoveLink: '删除链接',
          ilpEditorFileExisted: '文件已存在',
          ilpEditorFilesNotExist: '有些文件不存在',
          openFolder: '打开文件夹',
          playtest: '试玩',
          ilpEditorLinkProtocolLimit: '只支持https安全协议的链接',
          ilpEditorVersionLimit: '版本号需要大于 0',
          ilpVersionTip: '从数字1开始，后续更新文件再不断+1',
          steamWorkshop: 'Steam创意工坊',
          steamAuthorInfo: '作者信息',
          steamOpenAuthorInfoPage: '点击打开作者的Steam页面',
          steamAuthorOtherFiles: '作者的其它文件',
          steamSubscribeAndDownload: '订阅和下载',
          steamSubscribed: '已订阅',
          steamUnSubscribe: '取消订阅',
          steamUploading: '正在上传到Steam',
          shareToSteam: '分享到Steam创意工坊',
          steamUploadSuccess: '上传成功',
          viewFileInSteam: '在Steam中查看文件',
          saveToILPFile: '保存为ILP文件',
          uploadAgreement: '上传文件即同意了',
          agreementName: '创意工坊服务条款',
          selectSteamFileToUpdate: '选择Steam文件更新',
          steamMyFiles: '我的Steam文件',
          or: '或',
          dragToMove: '按住移动图片',
          clickToFind: '点击找出不同之处',
          doubleClickToReset: '双击重置位置和缩放',
          scrollToScale: '鼠标滚轮缩放图片',
          style: '风格',
          styleAnime: '动漫风格',
          styleRealistic: '写实风格',
          stylePixel: '像素风格',
          styleAncientChinese: '中国古代风格',
          styleOther: '其它',
          shape: '图片形状',
          landscape: '横向长方形',
          portrait: '纵向长方形',
          square: '正方形',
          ageRating: '年龄评级',
          ageEveryone: '所有人',
          ageQuestionable: '不确定',
          ageMature: '成年人',
          customTags: '自定义标签',
          tags: '标签',
          openInSteam: '在Steam中打开',
          fileSize: '文件大小',
          exportLogoExamplePSD: '导出PSD范例文件',
          openInBrowser: '在浏览器里打开',
        },
      };
}
